### ISSUE TITLE
Just a thank you note

### ISSUE THREAD

**Issue by ZoeBijl** [rtrvrtg/owlcarousel1-a11ylayer#2]
Thank you for this! That is all.

**Comment by rtrvrtg** [comment]
You're welcome. Sorry that it's still in a rough state and requires such a clunky method of attachment at this point. Owl Carousel v1 is kind of difficult to interact with in an API-based fashion, but we have to do our best with what we've got, right? I'm glad that you find the library useful - I'll hopefully be looking at improving this one, and working on more accessibility tools, when I find the time.
